# Generated by Django 3.1.1 on 2020-09-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_min', models.FloatField()),
                ('dia_max', models.FloatField()),
                ('a', models.SmallIntegerField()),
                ('c', models.SmallIntegerField()),
                ('d', models.SmallIntegerField()),
                ('e', models.SmallIntegerField()),
                ('f', models.SmallIntegerField()),
                ('g', models.SmallIntegerField()),
                ('h', models.SmallIntegerField()),
                ('j', models.SmallIntegerField()),
                ('k_under_IT7', models.SmallIntegerField()),
                ('k_above_IT7', models.SmallIntegerField()),
                ('m', models.SmallIntegerField()),
                ('n', models.SmallIntegerField()),
                ('p', models.SmallIntegerField()),
                ('r', models.SmallIntegerField()),
                ('s', models.SmallIntegerField()),
            ],
        ),
    ]
