# Generated by Django 3.1.1 on 2020-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_min', models.FloatField()),
                ('dia_max', models.FloatField()),
                ('a', models.SmallIntegerField()),
                ('c', models.SmallIntegerField()),
                ('d', models.SmallIntegerField()),
                ('e', models.SmallIntegerField()),
                ('f', models.SmallIntegerField()),
                ('g', models.SmallIntegerField()),
                ('h', models.SmallIntegerField()),
                ('j', models.SmallIntegerField()),
                ('k_under_IT7', models.SmallIntegerField()),
                ('k_above_IT7', models.SmallIntegerField()),
                ('m', models.SmallIntegerField()),
                ('n', models.SmallIntegerField()),
                ('p', models.SmallIntegerField()),
                ('r', models.SmallIntegerField()),
                ('s', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lambda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_min', models.FloatField()),
                ('dia_max', models.FloatField()),
                ('IT3', models.SmallIntegerField()),
                ('IT4', models.SmallIntegerField()),
                ('IT5', models.SmallIntegerField()),
                ('IT6', models.SmallIntegerField()),
                ('IT7', models.SmallIntegerField()),
                ('IT8', models.SmallIntegerField()),
            ],
        ),
    ]
