# Generated by Django 3.1.1 on 2020-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0002_hole_lambda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hole',
            old_name='k_above_IT7',
            new_name='k',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='k_under_IT7',
        ),
        migrations.AlterField(
            model_name='hole',
            name='dia_max',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='hole',
            name='dia_min',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lambda',
            name='dia_max',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lambda',
            name='dia_min',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='shaft',
            name='dia_max',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='shaft',
            name='dia_min',
            field=models.SmallIntegerField(),
        ),
    ]
