# Generated by Django 3.1.1 on 2020-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAD', '0003_auto_20200924_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_min', models.SmallIntegerField()),
                ('dia_max', models.SmallIntegerField()),
                ('IT1', models.SmallIntegerField()),
                ('IT2', models.SmallIntegerField()),
                ('IT3', models.SmallIntegerField()),
                ('IT4', models.SmallIntegerField()),
                ('IT5', models.SmallIntegerField()),
                ('IT6', models.SmallIntegerField()),
                ('IT7', models.SmallIntegerField()),
                ('IT8', models.SmallIntegerField()),
                ('IT9', models.SmallIntegerField()),
                ('IT10', models.SmallIntegerField()),
                ('IT11', models.SmallIntegerField()),
                ('IT12', models.SmallIntegerField()),
                ('IT13', models.SmallIntegerField()),
                ('IT14', models.SmallIntegerField()),
                ('IT15', models.SmallIntegerField()),
                ('IT16', models.SmallIntegerField()),
                ('IT17', models.SmallIntegerField()),
                ('IT18', models.SmallIntegerField()),
            ],
        ),
    ]
